version: '3'

services:
  nginx:
    image: cr.yandex/crpvc64qpcdbh5lbtlav/dt/vpn/bot/nginx:0.0.1
    ports:
      - "443:443" 
      - "80:80" 
    #restart: always
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    #   - ./ssl/site.crt:/etc/ssl/certs/site.crt
    #   - ./ssl/site.dec.key:/etc/ssl/private/site.dec.key
  bot:
    image: cr.yandex/crpvc64qpcdbh5lbtlav/dt/vpn/bot/app:0.0.1
    ports:
    - "8080:8080"
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-data: